### ISSUE TITLE
Why remove `active_border_color`?

### ISSUE THREAD

**Issue by briandipalma** [rose-pine/kitty#8]
I realize that the default colour doesn't match the theme but setting it to `none` makes it really hard to spot which window is active...would you consider setting it to one of the more obvious colours in the theme?

I mean for dawn there is zero difference between any window. It's really hard to spot the active one, I liked the old bright green border. Active tabs/buffers/windows should be quick and easy to spot I feel.

**Comment by mvllow** [comment]
Happy to set this to pine (used in the screenshot below) if that seems good to you?

Because I usually only have two windows open the separator border was consistently the "active" colour and didn't help distinguish between the two.

<img width="1440" alt="Two windows open inside kitty terminal with Rosé Pine theme, showing a green border around the active window" src="https://user-images.githubusercontent.com/1474821/222309045-29d67173-0630-4092-8abf-dca98aa9d197.png">

Once there are more than two windows, I can understand how having an active border colour is helpful :)

<img width="1440" alt="Three windows open inside kitty terminal with Rosé Pine theme, showing a green border around the active window" src="https://user-images.githubusercontent.com/1474821/222309483-ca6bd764-9de7-4d0e-b3ba-c65d4efb65e7.png">

**Comment by mvllow** [comment]
Rosé Pine Dawn with pine separator:

<img width="1440" alt="Three windows open inside kitty terminal using Rosé Pine Dawn theme, showing a green border around the active window" src="https://user-images.githubusercontent.com/1474821/222310071-f57bf5b8-f7ef-4737-8ee1-a0fea81303b1.png">

**Comment by briandipalma** [comment]
Yeah, I think that looks better.
